openapi: 3.2.0
info:
  description: The Onboarding API, groups together a pool of operations for the creation of a request for a digital bank account.
  version: v1
  title: Onboarding Expectedactivity API
servers:
- description: Sandbox
  url: https://sandbox-api.novopayment.com/onboarding/v1
security:
- oAuth2ClientCredentials: []
tags:
- name: Expectedactivity
paths:
  /expectedactivity:
    post:
      summary: Expected Account Activity
      description: This operation allows to save the responses of the expected account activity, defined by the tenant.
      requestBody:
        $ref: '#/components/requestBodies/RQExpectedAccountActivity'
      operationId: ExpectedAccountActivity
      responses:
        '200':
          $ref: '#/components/responses/RSExpectedAccountActivity200'
        '400':
          $ref: '#/components/responses/RSExpectedAccountActivity400'
        '401':
          $ref: '#/components/responses/RS401'
        '500':
          $ref: '#/components/responses/RS500'
      tags:
      - Expectedactivity
components:
  examples:
    InternalServerError:
      value:
        code: 500.25.001
        message: Internal Server Error
        datetime: '2020-01-03T16:05:56.517Z'
    InvalidData:
      value:
        code: 400.25.089
        message: Invalid data.
        datetime: '2020-01-03T16:05:56.517Z'
    InvalidAccessToken:
      value:
        code: 401.25.990
        message: Invalid Access Token
        datetime: '2020-01-03T16:05:56.517Z'
    AccessTokenNotApproved:
      value:
        code: 401.25.991
        message: Access Token not approved
        datetime: '2020-01-03T16:05:56.517Z'
    AccessTokenExpired:
      value:
        code: 401.25.993
        message: Access token expired
        datetime: '2020-01-03T16:05:56.517Z'
    InvalidSignature:
      value:
        code: 401.25.992
        message: Invalid signature
        datetime: '2020-01-03T16:05:56.517Z'
  schemas:
    RSExpectedAccountActivity400:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 400.25.003
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Params required
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RS500:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 500.01.999
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Internal Server Error
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          example: '2020-01-03T16:05:56.517Z'
          description: Opertion Timestamp
          format: date-time
    RS401:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 401.01.990
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Invalid Access Token
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RQExpectedAccountActivity:
      type: object
      required:
      - assesment
      properties:
        assesment:
          type: array
          description: Question and answer object.
          required:
          - questionId
          - answer
          items:
            type: object
            properties:
              questionId:
                type: integer
                description: Question identifier.
                example: 1
                maxLength: 38
              answer:
                type: array
                description: Answer object or answers to the question.
                required:
                - specification
                items:
                  type: object
                  properties:
                    specification:
                      type: string
                      description: Specification of the answer (s) to the question.
                      enum:
                      - 'yes'
                      - 'no'
    RSExpectedAccountActivity200:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          description: Operation response code
          example: 200.25.000
          maxLength: 10
        message:
          type: string
          description: Response code description
          example: Process Ok
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
  requestBodies:
    RQExpectedAccountActivity:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RQExpectedAccountActivity'
      required: true
  responses:
    RSExpectedAccountActivity400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSExpectedAccountActivity400'
          examples:
            Invalid Data:
              $ref: '#/components/examples/InvalidData'
    RSExpectedAccountActivity200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSExpectedAccountActivity200'
          examples:
            Success:
              value:
                code: 200.25.000
                message: Process Ok
                datetime: '2020-01-03T16:05:56.517Z'
    RS500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RS500'
          examples:
            Internal Server Error:
              $ref: '#/components/examples/InternalServerError'
    RS401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RS401'
          examples:
            Invalid Access Token:
              $ref: '#/components/examples/InvalidAccessToken'
            Access Token Not Approved:
              $ref: '#/components/examples/AccessTokenNotApproved'
            Invalid Signature:
              $ref: '#/components/examples/InvalidSignature'
            Access Token Expired:
              $ref: '#/components/examples/AccessTokenExpired'
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: 'See [Oauth2 API](https://developer.novopayment.com/api/authentication-method-and-encryption/oauth2-api)

        '
      flows:
        clientCredentials:
          tokenUrl: https://sandbox-api.novopayment.com/oauth2/token
          scopes: {}
