openapi: 3.2.0
info:
  title: Novopayment Documents API
  version: v1
  description: 'Operations tagged Documents across 2 of this provider''s published API definitions: novopayment-onboarding-openapi.yml, novopayment-profile-openapi.yml. Each path carries the servers of the definition it was published in.'
servers:
- description: Sandbox
  url: https://sandbox-api.novopayment.com/onboarding/v1
- description: Sandbox
  url: https://sandbox-api.novopayment.com/profiles/v1
security:
- oAuth2ClientCredentials: []
tags:
- name: Documents
paths:
  /documents:
    get:
      summary: Get Customer's Support Documents
      description: This operation checks the list of documents required for the verification and support of the account, which is requested based on the responses of previous actions in the registration process and the parameterization stipulated by the tenant.
      operationId: GetCustomersSupportDocuments
      responses:
        '200':
          $ref: '#/components/responses/RSGetCustomersSupportDocuments200'
        '400':
          $ref: '#/components/responses/RSGetCustomersSupportDocuments400'
        '401':
          $ref: '#/components/responses/RS401'
        '500':
          $ref: '#/components/responses/RS500'
      tags:
      - Documents
    post:
      summary: Upload Support Document
      description: This operation allows to register the documents requested for the account verification.
      requestBody:
        $ref: '#/components/requestBodies/RQUploadSupportDocument'
      operationId: UploadSupportDocument
      responses:
        '200':
          $ref: '#/components/responses/RSUploadSupportDocument200'
        '400':
          $ref: '#/components/responses/RSUploadSupportDocument400'
        '401':
          $ref: '#/components/responses/RS401'
        '500':
          $ref: '#/components/responses/RS500'
      tags:
      - Documents
    servers:
    - description: Sandbox
      url: https://sandbox-api.novopayment.com/onboarding/v1
  /{customerId}/documents:
    post:
      summary: Customer Document Upload
      description: This operation allows to upload of the requested documents for the validation of all the account information. Later, the tenant may request additional documents.
      requestBody:
        $ref: '#/components/requestBodies/RQCustomerDocumentUpload'
      operationId: CustomerDocumentUpload
      parameters:
      - $ref: '#/components/parameters/customerId'
      responses:
        '200':
          $ref: '#/components/responses/RSCustomerDocumentUpload200'
        '400':
          $ref: '#/components/responses/RSCustomerDocumentUpload400'
        '401':
          $ref: '#/components/responses/RS401'
        '500':
          $ref: '#/components/responses/RS500'
      tags:
      - Documents
    servers:
    - description: Sandbox
      url: https://sandbox-api.novopayment.com/profiles/v1
components:
  examples:
    InvalidData:
      value:
        code: 400.25.089
        message: Invalid data.
        datetime: '2020-01-03T16:05:56.517Z'
    AccessTokenExpired:
      value:
        code: 401.25.993
        message: Access token expired
        datetime: '2020-01-03T16:05:56.517Z'
    AccessTokenNotApproved:
      value:
        code: 401.25.991
        message: Access Token not approved
        datetime: '2020-01-03T16:05:56.517Z'
    RequestAcknowledgeFailure:
      value:
        code: 400.25.023
        message: It was not possible to acknowledge the request, please try again.
        datetime: '2020-01-03T16:05:56.517Z'
    InvalidSignature:
      value:
        code: 401.25.992
        message: Invalid signature
        datetime: '2020-01-03T16:05:56.517Z'
    InternalServerError:
      value:
        code: 500.25.001
        message: Internal Server Error
        datetime: '2020-01-03T16:05:56.517Z'
    ProcessNotCompleted:
      value:
        code: 400.25.019
        message: The process could not be completed.
        datetime: '2020-01-03T16:05:56.517Z'
    InvalidAccessToken:
      value:
        code: 401.25.990
        message: Invalid Access Token
        datetime: '2020-01-03T16:05:56.517Z'
    RequestAcknowledgeFailure_2:
      value:
        code: 400.02.023
        message: It was not possible to acknowledge the request, please try again.
        datetime: '2020-01-03T16:05:56.517Z'
  schemas:
    RSGetCustomersSupportDocuments400:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 400.25.003
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Params required
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RS500:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 500.01.999
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Internal Server Error
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          example: '2020-01-03T16:05:56.517Z'
          description: Opertion Timestamp
          format: date-time
    RSGetCustomersSupportDocuments200:
      type: object
      required:
      - code
      - message
      - datetime
      - data
      properties:
        code:
          type: string
          description: Operation response code
          example: 200.25.000
          maxLength: 10
        message:
          type: string
          description: Response code description
          example: Process Ok
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
        data:
          type: object
          required:
          - documents
          properties:
            documents:
              type: array
              required:
              - documentId
              - name
              - description
              - referenceDocumentLink
              - validExtension
              - minSize
              - maxSize
              - maxUploadDays
              - uploadDateLimit
              - uploadInformation
              items:
                type: object
                properties:
                  documentId:
                    type: integer
                    description: Document identifier.
                    example: 2
                    maxLength: 38
                  name:
                    type: string
                    description: Name of the document.
                    example: Proof of Employment
                    maxLength: 50
                  description:
                    type: string
                    description: Document detail.
                    example: Proof of employment issued by the company
                    maxLength: 200
                  referenceDocumentLink:
                    type: string
                    description: Document reference URL.
                    example: https://www.documents.com/pub/irs-pdf/fw8ben.pdf
                    maxLength: 100
                  validExtension:
                    type: string
                    description: 'Array of extensions allowed for loading the document.


                      __*Allowed values : [".xls, .pdf, .png"]__

                      '
                    example:
                    - pdf
                    maxLength: 100
                  minSize:
                    type: number
                    description: Minimum file size in kbs.
                    example: 54000
                    maxLength: 38
                  maxSize:
                    type: number
                    description: Maximum file weight in kbs.
                    example: 750000
                    maxLength: 38
                  maxUploadDays:
                    type: integer
                    description: Number of days to upload the file.
                    example: 15
                    maxLength: 38
                  uploadDateLimit:
                    type: string
                    description: Document upload deadline.
                    example: 2021-10-10
                  uploadInformation:
                    type: object
                    description: An object that contains the upload information for the file.
                    required:
                    - documentUploadId
                    - requestDate
                    - documentStatus
                    - fileInfo
                    properties:
                      documentUploadId:
                        type: integer
                        description: Document upload identifier.
                        example: 14
                        maxLength: 38
                      requestDate:
                        type: string
                        description: Document upload request date.
                        example: 2021-10-01
                      statusDoc:
                        type: object
                        description: Object that contains the status of the document.
                        required:
                        - statusId
                        - description
                        properties:
                          statusId:
                            type: integer
                            description: Document status identifier.
                            example: 1
                            maxLength: 38
                          description:
                            type: string
                            description: Description of the document status.
                            example: Uploaded
                            maxLength: 50
                      fileInfo:
                        type: object
                        description: An object that contains the information about the file when it is uploaded.
                        required:
                        - fileName
                        - fileSize
                        - extension
                        - uploadDate
                        properties:
                          fileName:
                            type: string
                            description: Uploaded file name.
                            example: proofofemploye.pdf
                            maxLength: 100
                          fileSize:
                            type: number
                            description: Uploaded File Size in kbs.
                            example: 78000
                            maxLength: 38
                          extension:
                            type: string
                            description: Extension of the uploaded file.
                            example: pdf
                            maxLength: 10
                          uploadDate:
                            type: string
                            description: Date the file was uploaded.
                            example: 2021-10-02
    RSUploadSupportDocument400:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 400.25.003
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Params required
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RS401:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 401.01.990
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Invalid Access Token
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RSUploadSupportDocument200:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          description: Operation response code
          example: 200.25.000
          maxLength: 10
        message:
          type: string
          description: Response code description
          example: Process Ok
          maxLength: 140
        datetime:
          type: string
          description: Opertion Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RQUploadSupportDocument:
      type: object
      required:
      - documentId
      - documentUploadId
      - fileInfo
      properties:
        documentId:
          type: string
          description: Document identifier.
          example: 1
          maxLength: 38
        documentUploadId:
          type: string
          description: Document upload identifier.
          example: 14
          maxLength: 38
        fileInfo:
          type: object
          description: An object that contains the information about the file when it is uploaded.
          required:
          - fileName
          - fileSize
          - extension
          - bytes
          properties:
            fileName:
              type: string
              description: Name of the uploaded file.
              example: proofofemploye.pdf
              maxLength: 100
            fileSize:
              type: number
              description: Size of the uploaded file in kbs.
              example: 78000
              maxLength: 38
            extension:
              type: string
              description: Extension of the uploaded file.
              example: pdf
              maxLength: 10
            bytes:
              type: string
              description: Base64 of the file to upload.
              example: JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFuZyhlcy1DTykgL1N0cnVjdFRyZWVSb290IDEwIDAgUi9NYXJrSW5mbzw8L01hcmtlZCB0cnVlPj4vTWV0YWRhdGEgMjAgMCBSL1ZpZXdlclByZWZlcmVuY2VzIDIxIDAgUj4+DQplbmRvYmoNCjIgMCBvYmoNCjw8L1R5cGUvUGFnZXMvQ291bnQgMS9LaWRzWyAzIDAgUl0gPj4NCmVuZG9iag0KMyAwIG9iag0KPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9SZXNvdXJjZXM8PC9Gb250PDwvRjEgNSAwIFI+Pi9FeHRHU3RhdGU8PC9HUzcgNyAwIFIvR1M4IDggMCBSPj4vUHJvY1NldFsvUERGL1RleHQvSW1hZ2VCL0ltYWdlQy9JbWFnZUldID4+L01lZGlhQm94WyAwIDAgNjEyIDc5Ml0gL0NvbnRlbnRzIDQgMCBSL0dyb3VwPDwvVHlwZS9Hcm91cC9TL1RyYW5zcGFyZW5jeSDUy9EZXZpY2VSR0I+Pi9UYWJzL1MvU3RydWN0UGFyZW50cyAwPj4NCmVuZG9iag0KNCAwIG9iag0KPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0xlbmd0aCAyMDA+Pg0Kc3RyZWFtDQp4nKWOOwvCQBCE+4P7D1PuCrncxpgYEAuTUxRjlEQsxMJCUxl8/H/wf
    RS500_2:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 500.01.999
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Internal Server Error
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          example: '2020-01-03T16:05:56.517Z'
          description: Operation Timestamp
          format: date-time
    RQCustomerDocumentUpload:
      type: object
      required:
      - documentId
      - documentUploadId
      - fileInfo
      properties:
        documentId:
          type: integer
          description: Document identifier.
          example: 1
          maxLength: 38
        documentUploadId:
          type: integer
          description: Document upload identifier.
          example: 1755
          maxLength: 38
        fileInfo:
          type: object
          description: Object that contains the file information when it is uploaded.
          required:
          - fileName
          - fileSize
          - extensión
          - bytes
          properties:
            fileName:
              type: string
              description: Uploaded file name.
              example: proofofemploye.pdf
              maxLength: 100
            fileSize:
              type: number
              description: Uploaded File Size in kbs.
              example: 37000
              maxLength: 38
            extensión:
              type: string
              description: File extension uploaded.
              example: pdf
              maxLength: 10
            bytes:
              type: string
              description: Base64 of the file to upload.
              example: JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFuZyhlcy1DTykgL1N0cnVjdFRyZWVSb290IDEwIDAgUi9NYXJrSW5mbzw8L01hcmtlZCB0cnVlPj4vTWV0YWRhdGEgMjAgMCBSL1ZpZXdlclByZWZlcmVuY2VzIDIxIDAgUj4+DQplbmRvYmoNCjIgMCBvYmoNCjw8L1R5cGUvUGFnZXMvQ291bnQgMS9LaWRzWyAzIDAgUl0gPj4NCmVuZG9iag0KMyAwIG9iag0KPDwvVHlwZS9QYWdlL1BhcmVudCAyIDAgUi9SZXNvdXJjZXM8PC9Gb250PDwvRjEgNSAwIFI+Pi9FeHRHU3RhdGU8PC9HUzcgNyAwIFIvR1M4IDggMCBSPj4vUHJvY1NldFsvUERGL1RleHQvSW1hZ2VCL0ltYWdlQy9JbWFnZUldID4+L01lZGlhQm94WyAwIDAgNjEyIDc5Ml0gL0NvbnRlbnRzIDQgMCBSL0dyb3VwPDwvVHlwZS9Hcm91cC9TL1RyYW5zcGFyZW5jeS9DUy9EZXZpY2VSR0I+Pi9UYWJzL1MvU3RydWN0UGFyZW50cyAwPj4NCmVuZG9iag0KNCAwIG9iag0KPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0xlbmd0aCAyMDA+Pg0Kc3RyZWFtDQp4nKWOOwvCQBCE+4P7D1PuCrncxpgYEAuTUxRjlEQsxMJCUxl8/H/wfDTWbrHs7Ay7H8L6euwwGoVlPi9gw+Wxa0GnR+BqHo8xKXLctLLGviqTCBaJ72kW4X7SatdDp9Wk0SqcCkSMjdGctRKfsxAMB0b8KhVrUu9cfG5Wp2gf/ibatxp+1UyrPRUcxFTlWxahkoM+uRXH1HBGFTiIyC0cS/Sx1pzQ8jVUfECz0Mp5jI1W//BKZk3/h/eN+aXD7yO4MscTHM0=
    RSCustomerDocumentUpload400:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 400.25.003
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Params required
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          description: Operation Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RSCustomerDocumentUpload200:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          description: Operation response code
          example: 200.25.000
          maxLength: 10
        message:
          type: string
          description: Response code description
          example: Process Ok
          maxLength: 140
        datetime:
          type: string
          description: Operation Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
    RS401_2:
      type: object
      required:
      - code
      - message
      - datetime
      properties:
        code:
          type: string
          example: 401.01.990
          description: Operation response code
          minLength: 10
          maxLength: 10
        message:
          type: string
          example: Invalid Access Token
          description: Response code description
          maxLength: 140
        datetime:
          type: string
          description: Operation Timestamp
          example: '2020-01-03T16:05:56.517Z'
          format: date-time
  responses:
    RS500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RS500'
          examples:
            Internal Server Error:
              $ref: '#/components/examples/InternalServerError'
    RSUploadSupportDocument400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSUploadSupportDocument400'
          examples:
            Process Not Completed:
              $ref: '#/components/examples/ProcessNotCompleted'
            Request Acknowledge Failure:
              $ref: '#/components/examples/RequestAcknowledgeFailure'
    RSGetCustomersSupportDocuments400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSGetCustomersSupportDocuments400'
          examples:
            Invalid Data:
              $ref: '#/components/examples/InvalidData'
    RSUploadSupportDocument200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSUploadSupportDocument200'
          examples:
            Success:
              value:
                code: 200.25.000
                message: Process Ok
                datetime: '2020-01-03T16:05:56.517Z'
    RS401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RS401'
          examples:
            Invalid Access Token:
              $ref: '#/components/examples/InvalidAccessToken'
            Access Token Not Approved:
              $ref: '#/components/examples/AccessTokenNotApproved'
            Invalid Signature:
              $ref: '#/components/examples/InvalidSignature'
            Access Token Expired:
              $ref: '#/components/examples/AccessTokenExpired'
    RSGetCustomersSupportDocuments200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSGetCustomersSupportDocuments200'
          examples:
            Success:
              value:
                code: 200.25.000
                message: Process Ok
                datetime: '2020-01-03T16:05:56.517Z'
                data:
                  documents:
                  - documentId: 2
                    name: Proof of Employe
                    description: Proof of employment issued by the company
                    referenceDocumentLink: https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
                    validExtension:
                    - .xls
                    - .pdf
                    - .png
                    minSize: 54000
                    maxSize: 750000
                    maxUploadDays: 15
                    uploadDateLimit: '2021-10-10'
                    uploadInformation:
                      documentUploadId: 14
                      requestedDate: '2021-10-01'
                      statusDoc:
                        statusId: 1
                        description: Uploaded
                      fileInfo:
                        fileName: proofofemploye.pdf
                        fileSize: 78000
                        extension: pdf
                        uploadDate: '2021-10-02'
    RSCustomerDocumentUpload200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSCustomerDocumentUpload200'
          examples:
            Success:
              value:
                code: 200.25.000
                message: Process Ok
                datetime: '2020-01-03T16:05:56.517Z'
    RSCustomerDocumentUpload400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RSCustomerDocumentUpload400'
          examples:
            Request Acknowledge Failure:
              $ref: '#/components/examples/RequestAcknowledgeFailure_2'
  requestBodies:
    RQUploadSupportDocument:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RQUploadSupportDocument'
      required: true
    RQCustomerDocumentUpload:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RQCustomerDocumentUpload'
      required: true
  parameters:
    customerId:
      name: customerId
      in: path
      description: Unique customer identifier.
      required: true
      schema:
        type: string
        example: 43DED66474E259FD
        maxLength: 40
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: 'See [Oauth2 API](https://developer.novopayment.com/api/authentication-method-and-encryption/oauth2-api)

        '
      flows:
        clientCredentials:
          tokenUrl: https://sandbox-api.novopayment.com/oauth2/token
          scopes: {}
x-refined-from:
- novopayment-onboarding-openapi.yml
- novopayment-profile-openapi.yml
